# Generated by Django 3.0.2 on 2020-02-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20200227_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
