# Generated by Django 3.0.2 on 2020-02-28 22:29

from django.db import migrations, models
import workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_auto_20200228_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopimage',
            name='image',
            field=models.ImageField(upload_to=workshops.models.get_image_filename),
        ),
    ]
